### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'version'

### ISSUE THREAD

**Issue by kbaikov** [dhellmann/whatthewhat#1]
Just running wtw or wtw somefile.py gives an exception:

Traceback (most recent call last):
  File "C:\Python33\Scripts\wtw-script.py", line 9, in <module>
    load_entry_point('whatthewhat==1.0', 'console_scripts', 'wtw')()
  File "C:\Python33\lib\site-packages\whatthewhat\main.py", line 41, in main
    version=dist.version,
TypeError: **init**() got an unexpected keyword argument 'version'

Win 8.1
Python 3.3.4 (v3.3.4:7ff62415e426, Feb 10 2014, 18:13:51) [MSC v.1600 64 bit (AMD64)] on win32
setuptools 2.2

**Comment by dhellmann** [comment]
That's a python 3 change. I'm afraid whatthewhat isn't compatible with python 3, yet.
